repos:
  - repo: https://github.com/myint/autoflake
    rev: v1.4
    hooks:
      - id: autoflake
        entry: autoflake -i --remove-all-unused-imports
  - repo: https://github.com/ambv/black
    rev: 21.12b0
    hooks:
      - id: black
  - repo: https://github.com/timothycrosley/isort
    rev: 5.10.1
    hooks:
      - id: isort
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.910
    hooks:
      - id: mypy
        args: [ --disallow-untyped-defs, --strict-optional]
        additional_dependencies:
          - django
          - django-stubs
          - django-rest-framework
          - djangorestframework-stubs
          - psycopg2
