[tool.black]
line-length = 100
skip-string-normalization = true
exclude = 'migrations/'

[tool.mypy]
python_version = '3.10'
plugins = ['mypy_django_plugin.main', 'mypy_drf_plugin.main']
ignore_missing_imports = true
disallow_untyped_defs = true
strict_optional = true

[tool.django-stubs]
django_settings_module = 'AAPI.settings'
